version: '3.8'

services:
  phishing-detector:
    build: .
    ports:
      - "8003:8003"
    environment:
      - HOST=0.0.0.0
      - PORT=8003
      - PYTHONUNBUFFERED=1
    volumes:
      - ./reports:/app/reports
      - ./static:/app/static
      - ./templates:/app/templates
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8003/health', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - phishing-detector
    restart: unless-stopped
    profiles:
      - production